var tokens = [];
tokens[0] = [{"token":0,"type":"callDuration","data":{"callEvent":"CALL_START","time":1331211295810}}, {"token":1,"type":"callDuration","data":{"callEvent":"CERTIFICATECOURSE_START","time":1331211297476}},{"token":2,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a66d5","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 1 Lesson 1","time":"2012-03-08T12:54:57Z","chapterIndex":0,"lessonOrQuestionIndex":0}}];
tokens[1] = [{"token":3,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a807e","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 1 Lesson 2","time":"2012-03-08T12:55:18Z","chapterIndex":0,"lessonOrQuestionIndex":1}}];
tokens[2] = [{"token":4,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a807e","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 1 Lesson 2","time":"2012-03-08T12:55:31Z","chapterIndex":0,"lessonOrQuestionIndex":1}}];
tokens[3] = [{"token":5,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a99ed","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 1 Lesson 3","time":"2012-03-08T12:55:33Z","chapterIndex":0,"lessonOrQuestionIndex":2}}];
tokens[4] = [{"token":6,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a99ed","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 1 Lesson 3","time":"2012-03-08T12:55:35Z","chapterIndex":0,"lessonOrQuestionIndex":2}}];
tokens[5] = [{"token":7,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ab0e2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 1 Lesson 4","time":"2012-03-08T12:55:37Z","chapterIndex":0,"lessonOrQuestionIndex":3}}];
tokens[6] = [{"token":8,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ab0e2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 1 Lesson 4","time":"2012-03-08T12:55:41Z","chapterIndex":0,"lessonOrQuestionIndex":3}}];
tokens[7] = [{"token":9,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a556f","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 1","time":"2012-03-08T12:55:45Z","chapterIndex":0,"lessonOrQuestionIndex":3}}];
tokens[8] = [{"token":10,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:55:47Z","chapterIndex":0,"lessonOrQuestionIndex":4}}];
tokens[9] = [{"token":11,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:55:56Z","chapterIndex":0,"lessonOrQuestionIndex":4}}];
tokens[10] = [{"token":12,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:00Z","chapterIndex":0,"lessonOrQuestionIndex":5}}];
tokens[11] = [{"token":13,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:02Z","chapterIndex":0,"lessonOrQuestionIndex":5}}];
tokens[12] = [{"token":14,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:05Z","chapterIndex":0,"lessonOrQuestionIndex":6}}];
tokens[13] = [{"token":15,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:08Z","chapterIndex":0,"lessonOrQuestionIndex":6}}];
tokens[14] = [{"token":16,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:12Z","chapterIndex":0,"lessonOrQuestionIndex":7}}];
tokens[15] = [{"token":17,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:14Z","chapterIndex":0,"lessonOrQuestionIndex":7}}];
tokens[16] = [{"token":18,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a556f","contentType":"quiz","certificateCourseId":"","contentData":"3","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 1","time":"2012-03-08T12:56:16Z","chapterIndex":0,"lessonOrQuestionIndex":7}}];
tokens[17] = [{"token":19,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6a556f","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 1","time":"2012-03-08T12:56:18Z","chapterIndex":0,"lessonOrQuestionIndex":7}}];
tokens[18] = [{"token":20,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6b843a","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 2","time":"2012-03-08T12:56:22Z","chapterIndex":1,"lessonOrQuestionIndex":0}},{"token":21,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6b9eb2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 2 Lesson 1","time":"2012-03-08T12:56:22Z","chapterIndex":1,"lessonOrQuestionIndex":0}}];
tokens[19] = [{"token":22,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6b9eb2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 2 Lesson 1","time":"2012-03-08T12:56:25Z","chapterIndex":1,"lessonOrQuestionIndex":0}}];
tokens[20] = [{"token":23,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6bab7b","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 2 Lesson 2","time":"2012-03-08T12:56:29Z","chapterIndex":1,"lessonOrQuestionIndex":1}}];
tokens[21] = [{"token":24,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6bab7b","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 2 Lesson 2","time":"2012-03-08T12:56:31Z","chapterIndex":1,"lessonOrQuestionIndex":1}}];
tokens[22] = [{"token":25,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6bcc83","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 2 Lesson 3","time":"2012-03-08T12:56:32Z","chapterIndex":1,"lessonOrQuestionIndex":2}}];
tokens[23] = [{"token":26,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6bcc83","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 2 Lesson 3","time":"2012-03-08T12:56:33Z","chapterIndex":1,"lessonOrQuestionIndex":2}}];
tokens[24] = [{"token":27,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6bda92","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 2 Lesson 4","time":"2012-03-08T12:56:34Z","chapterIndex":1,"lessonOrQuestionIndex":3}}];
tokens[25] = [{"token":28,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6bda92","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 2 Lesson 4","time":"2012-03-08T12:56:35Z","chapterIndex":1,"lessonOrQuestionIndex":3}}];
tokens[26] = [{"token":29,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6b843a","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 2","time":"2012-03-08T12:56:36Z","chapterIndex":1,"lessonOrQuestionIndex":3}}];
tokens[27] = [{"token":30,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:38Z","chapterIndex":1,"lessonOrQuestionIndex":4}}];
tokens[28] = [{"token":31,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:42Z","chapterIndex":1,"lessonOrQuestionIndex":4}}];
tokens[29] = [{"token":32,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:45Z","chapterIndex":1,"lessonOrQuestionIndex":5}}];
tokens[30] = [{"token":33,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:47Z","chapterIndex":1,"lessonOrQuestionIndex":5}}];
tokens[31] = [{"token":34,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:49Z","chapterIndex":1,"lessonOrQuestionIndex":6}}];
tokens[32] = [{"token":35,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:50Z","chapterIndex":1,"lessonOrQuestionIndex":6}}];
tokens[33] = [{"token":36,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:56:52Z","chapterIndex":1,"lessonOrQuestionIndex":7}}];
tokens[34] = [{"token":37,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:56:54Z","chapterIndex":1,"lessonOrQuestionIndex":7}}];
tokens[35] = [{"token":38,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6b843a","contentType":"quiz","certificateCourseId":"","contentData":"4","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 2","time":"2012-03-08T12:56:56Z","chapterIndex":1,"lessonOrQuestionIndex":7}}];
tokens[36] = [{"token":39,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6b843a","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 2","time":"2012-03-08T12:56:57Z","chapterIndex":1,"lessonOrQuestionIndex":7}}];
tokens[37] = [{"token":40,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6c8ff5","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 3","time":"2012-03-08T12:56:59Z","chapterIndex":2,"lessonOrQuestionIndex":0}},{"token":41,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6cab5f","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 3 Lesson 1","time":"2012-03-08T12:56:59Z","chapterIndex":2,"lessonOrQuestionIndex":0}}];
tokens[38] = [{"token":42,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6cab5f","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 3 Lesson 1","time":"2012-03-08T12:57:01Z","chapterIndex":2,"lessonOrQuestionIndex":0}}];
tokens[39] = [{"token":43,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ccf25","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 3 Lesson 2","time":"2012-03-08T12:57:02Z","chapterIndex":2,"lessonOrQuestionIndex":1}}];
tokens[40] = [{"token":44,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ccf25","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 3 Lesson 2","time":"2012-03-08T12:57:02Z","chapterIndex":2,"lessonOrQuestionIndex":1}}];
tokens[41] = [{"token":45,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6cde44","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 3 Lesson 3","time":"2012-03-08T12:57:03Z","chapterIndex":2,"lessonOrQuestionIndex":2}}];
tokens[42] = [{"token":46,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6cde44","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 3 Lesson 3","time":"2012-03-08T12:57:03Z","chapterIndex":2,"lessonOrQuestionIndex":2}}];
tokens[43] = [{"token":47,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6cf0d4","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 3 Lesson 4","time":"2012-03-08T12:57:04Z","chapterIndex":2,"lessonOrQuestionIndex":3}}];
tokens[44] = [{"token":48,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6cf0d4","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 3 Lesson 4","time":"2012-03-08T12:57:05Z","chapterIndex":2,"lessonOrQuestionIndex":3}}];
tokens[45] = [{"token":49,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6c8ff5","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 3","time":"2012-03-08T12:57:06Z","chapterIndex":2,"lessonOrQuestionIndex":3}}];
tokens[46] = [{"token":50,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:09Z","chapterIndex":2,"lessonOrQuestionIndex":4}}];
tokens[47] = [{"token":51,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:16Z","chapterIndex":2,"lessonOrQuestionIndex":4}}];
tokens[48] = [{"token":52,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:17Z","chapterIndex":2,"lessonOrQuestionIndex":5}}];
tokens[49] = [{"token":53,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:18Z","chapterIndex":2,"lessonOrQuestionIndex":5}}];
tokens[50] = [{"token":54,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:19Z","chapterIndex":2,"lessonOrQuestionIndex":6}}];
tokens[51] = [{"token":55,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:20Z","chapterIndex":2,"lessonOrQuestionIndex":6}}];
tokens[52] = [{"token":56,"type":"ccState","data":{"result":true,"questionResponse":"1","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:22Z","chapterIndex":2,"lessonOrQuestionIndex":7}}];
tokens[53] = [{"token":57,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:23Z","chapterIndex":2,"lessonOrQuestionIndex":7}}];
tokens[54] = [{"token":58,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6c8ff5","contentType":"quiz","certificateCourseId":"","contentData":"4","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 3","time":"2012-03-08T12:57:23Z","chapterIndex":2,"lessonOrQuestionIndex":7}}];
tokens[55] = [{"token":59,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6c8ff5","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 3","time":"2012-03-08T12:57:24Z","chapterIndex":2,"lessonOrQuestionIndex":7}}];
tokens[56] = [{"token":60,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dbde0","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 4","time":"2012-03-08T12:57:24Z","chapterIndex":3,"lessonOrQuestionIndex":0}},{"token":61,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dd712","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 4 Lesson 1","time":"2012-03-08T12:57:24Z","chapterIndex":3,"lessonOrQuestionIndex":0}}];
tokens[57] = [{"token":62,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dd712","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 4 Lesson 1","time":"2012-03-08T12:57:25Z","chapterIndex":3,"lessonOrQuestionIndex":0}}];
tokens[58] = [{"token":63,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6de702","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 4 Lesson 2","time":"2012-03-08T12:57:25Z","chapterIndex":3,"lessonOrQuestionIndex":1}}];
tokens[59] = [{"token":64,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6de702","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 4 Lesson 2","time":"2012-03-08T12:57:25Z","chapterIndex":3,"lessonOrQuestionIndex":1}}];
tokens[60] = [{"token":65,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dfe06","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 4 Lesson 3","time":"2012-03-08T12:57:26Z","chapterIndex":3,"lessonOrQuestionIndex":2}}];
tokens[61] = [{"token":66,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dfe06","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 4 Lesson 3","time":"2012-03-08T12:57:26Z","chapterIndex":3,"lessonOrQuestionIndex":2}}];
tokens[62] = [{"token":67,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6e1509","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 4 Lesson 4","time":"2012-03-08T12:57:26Z","chapterIndex":3,"lessonOrQuestionIndex":3}}];
tokens[63] = [{"token":68,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6e1509","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 4 Lesson 4","time":"2012-03-08T12:57:27Z","chapterIndex":3,"lessonOrQuestionIndex":3}}];
tokens[64] = [{"token":69,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dbde0","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 4","time":"2012-03-08T12:57:28Z","chapterIndex":3,"lessonOrQuestionIndex":3}}];
tokens[65] = [{"token":70,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:30Z","chapterIndex":3,"lessonOrQuestionIndex":4}}];
tokens[66] = [{"token":71,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:31Z","chapterIndex":3,"lessonOrQuestionIndex":4}}];
tokens[67] = [{"token":72,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:31Z","chapterIndex":3,"lessonOrQuestionIndex":5}}];
tokens[68] = [{"token":73,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:31Z","chapterIndex":3,"lessonOrQuestionIndex":5}}];
tokens[69] = [{"token":74,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:32Z","chapterIndex":3,"lessonOrQuestionIndex":6}}];
tokens[70] = [{"token":75,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:32Z","chapterIndex":3,"lessonOrQuestionIndex":6}}];
tokens[71] = [{"token":76,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:57:39Z","chapterIndex":3,"lessonOrQuestionIndex":7}}];
tokens[72] = [{"token":77,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:57:40Z","chapterIndex":3,"lessonOrQuestionIndex":7}}];
tokens[73] = [{"token":78,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dbde0","contentType":"quiz","certificateCourseId":"","contentData":"2","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 4","time":"2012-03-08T12:57:40Z","chapterIndex":3,"lessonOrQuestionIndex":7}}];
tokens[74] = [{"token":79,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dbde0","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 4","time":"2012-03-08T12:57:41Z","chapterIndex":3,"lessonOrQuestionIndex":7}}];
tokens[75] = [{"token":80,"type":"callDuration","data":{"callEvent":"CALL_START","time":1331211511405}},{"token":81,"type":"callDuration","data":{"callEvent":"CERTIFICATECOURSE_START","time":1331211511526}},{"token":82,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6dbde0","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 4","time":"2012-03-08T12:58:31Z","chapterIndex":3,"lessonOrQuestionIndex":7}}];
tokens[76] = [{"token":83,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ea919","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 5","time":"2012-03-08T12:58:38Z","chapterIndex":4,"lessonOrQuestionIndex":0}},{"token":84,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6eba78","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 5 Lesson 1","time":"2012-03-08T12:58:38Z","chapterIndex":4,"lessonOrQuestionIndex":0}}];
tokens[77] = [{"token":85,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6eba78","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 5 Lesson 1","time":"2012-03-08T12:58:39Z","chapterIndex":4,"lessonOrQuestionIndex":0}}];
tokens[78] = [{"token":86,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ecd8f","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 5 Lesson 2","time":"2012-03-08T12:58:40Z","chapterIndex":4,"lessonOrQuestionIndex":1}}];
tokens[79] = [{"token":87,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ecd8f","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 5 Lesson 2","time":"2012-03-08T12:58:41Z","chapterIndex":4,"lessonOrQuestionIndex":1}}];
tokens[80] = [{"token":88,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ee4ed","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 5 Lesson 3","time":"2012-03-08T12:58:42Z","chapterIndex":4,"lessonOrQuestionIndex":2}}];
tokens[81] = [{"token":89,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ee4ed","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 5 Lesson 3","time":"2012-03-08T12:58:43Z","chapterIndex":4,"lessonOrQuestionIndex":2}}];
tokens[82] = [{"token":90,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6eee1f","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 5 Lesson 4","time":"2012-03-08T12:58:43Z","chapterIndex":4,"lessonOrQuestionIndex":3}}];
tokens[83] = [{"token":91,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6eee1f","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 5 Lesson 4","time":"2012-03-08T12:58:44Z","chapterIndex":4,"lessonOrQuestionIndex":3}}];
tokens[84] = [{"token":92,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ea919","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 5","time":"2012-03-08T12:58:45Z","chapterIndex":4,"lessonOrQuestionIndex":3}}];
tokens[85] = [{"token":93,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:58:45Z","chapterIndex":4,"lessonOrQuestionIndex":4}}];
tokens[86] = [{"token":94,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:58:46Z","chapterIndex":4,"lessonOrQuestionIndex":4}}];
tokens[87] = [{"token":95,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:58:47Z","chapterIndex":4,"lessonOrQuestionIndex":5}}];
tokens[88] = [{"token":96,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:58:48Z","chapterIndex":4,"lessonOrQuestionIndex":5}}];
tokens[89] = [{"token":97,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:58:48Z","chapterIndex":4,"lessonOrQuestionIndex":6}}];
tokens[90] = [{"token":98,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:58:49Z","chapterIndex":4,"lessonOrQuestionIndex":6}}];
tokens[91] = [{"token":99,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:58:49Z","chapterIndex":4,"lessonOrQuestionIndex":7}}];
tokens[92] = [{"token":100,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:58:50Z","chapterIndex":4,"lessonOrQuestionIndex":7}}];
tokens[93] = [{"token":101,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ea919","contentType":"quiz","certificateCourseId":"","contentData":"2","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 5","time":"2012-03-08T12:58:51Z","chapterIndex":4,"lessonOrQuestionIndex":7}}];
tokens[94] = [{"token":102,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6ea919","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 5","time":"2012-03-08T12:58:52Z","chapterIndex":4,"lessonOrQuestionIndex":7}}];
tokens[95] = [{"token":103,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6fac81","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 6","time":"2012-03-08T12:58:52Z","chapterIndex":5,"lessonOrQuestionIndex":0}},{"token":104,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6fcec7","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 6 Lesson 1","time":"2012-03-08T12:58:52Z","chapterIndex":5,"lessonOrQuestionIndex":0}}];
tokens[96] = [{"token":105,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6fcec7","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 6 Lesson 1","time":"2012-03-08T12:58:53Z","chapterIndex":5,"lessonOrQuestionIndex":0}}];
tokens[97] = [{"token":106,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6febb6","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 6 Lesson 2","time":"2012-03-08T12:58:54Z","chapterIndex":5,"lessonOrQuestionIndex":1}}];
tokens[98] = [{"token":107,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6febb6","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 6 Lesson 2","time":"2012-03-08T12:58:54Z","chapterIndex":5,"lessonOrQuestionIndex":1}}];
tokens[99] = [{"token":108,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70033b","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 6 Lesson 3","time":"2012-03-08T12:58:55Z","chapterIndex":5,"lessonOrQuestionIndex":2}}];
tokens[100] = [{"token":109,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70033b","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 6 Lesson 3","time":"2012-03-08T12:58:56Z","chapterIndex":5,"lessonOrQuestionIndex":2}}];
tokens[101] = [{"token":110,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70232d","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 6 Lesson 4","time":"2012-03-08T12:58:56Z","chapterIndex":5,"lessonOrQuestionIndex":3}}];
tokens[102] = [{"token":111,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70232d","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 6 Lesson 4","time":"2012-03-08T12:58:57Z","chapterIndex":5,"lessonOrQuestionIndex":3}}];
tokens[103] = [{"token":112,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6fac81","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 6","time":"2012-03-08T12:58:58Z","chapterIndex":5,"lessonOrQuestionIndex":3}}];
tokens[104] = [{"token":113,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:58:58Z","chapterIndex":5,"lessonOrQuestionIndex":4}}];
tokens[105] = [{"token":114,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:58:59Z","chapterIndex":5,"lessonOrQuestionIndex":4}}];
tokens[106] = [{"token":115,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:00Z","chapterIndex":5,"lessonOrQuestionIndex":5}}];
tokens[107] = [{"token":116,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:01Z","chapterIndex":5,"lessonOrQuestionIndex":5}}];
tokens[108] = [{"token":117,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:01Z","chapterIndex":5,"lessonOrQuestionIndex":6}}];
tokens[109] = [{"token":118,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:02Z","chapterIndex":5,"lessonOrQuestionIndex":6}}];
tokens[110] = [{"token":119,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:03Z","chapterIndex":5,"lessonOrQuestionIndex":7}}];
tokens[111] = [{"token":120,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:04Z","chapterIndex":5,"lessonOrQuestionIndex":7}}];
tokens[112] = [{"token":121,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6fac81","contentType":"quiz","certificateCourseId":"","contentData":"2","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 6","time":"2012-03-08T12:59:04Z","chapterIndex":5,"lessonOrQuestionIndex":7}}];
tokens[113] = [{"token":122,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed6fac81","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 6","time":"2012-03-08T12:59:05Z","chapterIndex":5,"lessonOrQuestionIndex":7}}];
tokens[114] = [{"token":123,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70e832","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 7","time":"2012-03-08T12:59:06Z","chapterIndex":6,"lessonOrQuestionIndex":0}},{"token":124,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed710227","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 7 Lesson 1","time":"2012-03-08T12:59:06Z","chapterIndex":6,"lessonOrQuestionIndex":0}}];
tokens[115] = [{"token":125,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed710227","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 7 Lesson 1","time":"2012-03-08T12:59:07Z","chapterIndex":6,"lessonOrQuestionIndex":0}}];
tokens[116] = [{"token":126,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7118ab","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 7 Lesson 2","time":"2012-03-08T12:59:07Z","chapterIndex":6,"lessonOrQuestionIndex":1}}];
tokens[117] = [{"token":127,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7118ab","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 7 Lesson 2","time":"2012-03-08T12:59:08Z","chapterIndex":6,"lessonOrQuestionIndex":1}}];
tokens[118] = [{"token":128,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7131e2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 7 Lesson 3","time":"2012-03-08T12:59:09Z","chapterIndex":6,"lessonOrQuestionIndex":2}}];
tokens[119] = [{"token":129,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7131e2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 7 Lesson 3","time":"2012-03-08T12:59:10Z","chapterIndex":6,"lessonOrQuestionIndex":2}}];
tokens[120] = [{"token":130,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7154a5","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 7 Lesson 4","time":"2012-03-08T12:59:10Z","chapterIndex":6,"lessonOrQuestionIndex":3}}];
tokens[121] = [{"token":131,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7154a5","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 7 Lesson 4","time":"2012-03-08T12:59:11Z","chapterIndex":6,"lessonOrQuestionIndex":3}}];
tokens[122] = [{"token":132,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70e832","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 7","time":"2012-03-08T12:59:12Z","chapterIndex":6,"lessonOrQuestionIndex":3}}];
tokens[123] = [{"token":133,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:12Z","chapterIndex":6,"lessonOrQuestionIndex":4}}];
tokens[124] = [{"token":134,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:13Z","chapterIndex":6,"lessonOrQuestionIndex":4}}];
tokens[125] = [{"token":135,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:14Z","chapterIndex":6,"lessonOrQuestionIndex":5}}];
tokens[126] = [{"token":136,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:14Z","chapterIndex":6,"lessonOrQuestionIndex":5}}];
tokens[127] = [{"token":137,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:15Z","chapterIndex":6,"lessonOrQuestionIndex":6}}];
tokens[128] = [{"token":138,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:16Z","chapterIndex":6,"lessonOrQuestionIndex":6}}];
tokens[129] = [{"token":139,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:16Z","chapterIndex":6,"lessonOrQuestionIndex":7}}];
tokens[130] = [{"token":140,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:17Z","chapterIndex":6,"lessonOrQuestionIndex":7}}];
tokens[131] = [{"token":141,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70e832","contentType":"quiz","certificateCourseId":"","contentData":"2","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 7","time":"2012-03-08T12:59:18Z","chapterIndex":6,"lessonOrQuestionIndex":7}}];
tokens[132] = [{"token":142,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed70e832","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 7","time":"2012-03-08T12:59:18Z","chapterIndex":6,"lessonOrQuestionIndex":7}}];
tokens[133] = [{"token":143,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7215cb","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 8","time":"2012-03-08T12:59:19Z","chapterIndex":7,"lessonOrQuestionIndex":0}},{"token":144,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed722900","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 8 Lesson 1","time":"2012-03-08T12:59:19Z","chapterIndex":7,"lessonOrQuestionIndex":0}}];
tokens[134] = [{"token":145,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed722900","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 8 Lesson 1","time":"2012-03-08T12:59:20Z","chapterIndex":7,"lessonOrQuestionIndex":0}}];
tokens[135] = [{"token":146,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed72328d","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 8 Lesson 2","time":"2012-03-08T12:59:21Z","chapterIndex":7,"lessonOrQuestionIndex":1}}];
tokens[136] = [{"token":147,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed72328d","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 8 Lesson 2","time":"2012-03-08T12:59:21Z","chapterIndex":7,"lessonOrQuestionIndex":1}}];
tokens[137] = [{"token":148,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed724074","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 8 Lesson 3","time":"2012-03-08T12:59:22Z","chapterIndex":7,"lessonOrQuestionIndex":2}}];
tokens[138] = [{"token":149,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed724074","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 8 Lesson 3","time":"2012-03-08T12:59:24Z","chapterIndex":7,"lessonOrQuestionIndex":2}}];
tokens[139] = [{"token":150,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed724802","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 8 Lesson 4","time":"2012-03-08T12:59:25Z","chapterIndex":7,"lessonOrQuestionIndex":3}}];
tokens[140] = [{"token":151,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed724802","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 8 Lesson 4","time":"2012-03-08T12:59:26Z","chapterIndex":7,"lessonOrQuestionIndex":3}}];
tokens[141] = [{"token":152,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7215cb","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 8","time":"2012-03-08T12:59:27Z","chapterIndex":7,"lessonOrQuestionIndex":3}}];
tokens[142] = [{"token":153,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:28Z","chapterIndex":7,"lessonOrQuestionIndex":4}}];
tokens[143] = [{"token":154,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:29Z","chapterIndex":7,"lessonOrQuestionIndex":4}}];
tokens[144] = [{"token":155,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:30Z","chapterIndex":7,"lessonOrQuestionIndex":5}}];
tokens[145] = [{"token":156,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:30Z","chapterIndex":7,"lessonOrQuestionIndex":5}}];
tokens[146] = [{"token":157,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:31Z","chapterIndex":7,"lessonOrQuestionIndex":6}}];
tokens[147] = [{"token":158,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:32Z","chapterIndex":7,"lessonOrQuestionIndex":6}}];
tokens[148] = [{"token":159,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T12:59:33Z","chapterIndex":7,"lessonOrQuestionIndex":7}}];
tokens[149] = [{"token":160,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T12:59:33Z","chapterIndex":7,"lessonOrQuestionIndex":7}}];
tokens[150] = [{"token":161,"type":"callDuration","data":{"callEvent":"CALL_START","time":1331211585997}},{"token":162,"type":"callDuration","data":{"callEvent":"CERTIFICATECOURSE_START","time":1331211586096}},{"token":163,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7215cb","contentType":"quiz","certificateCourseId":"","contentData":"2","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 8","time":"2012-03-08T12:59:46Z","chapterIndex":7,"lessonOrQuestionIndex":7}}];
tokens[151] = [{"token":164,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7215cb","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 8","time":"2012-03-08T12:59:52Z","chapterIndex":7,"lessonOrQuestionIndex":7}}];
tokens[152] = [{"token":165,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed732634","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"startNextChapter","courseItemState":"start","contentName":"Chapter 9","time":"2012-03-08T12:59:57Z","chapterIndex":8,"lessonOrQuestionIndex":0}},{"token":166,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed734b03","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 9 Lesson 1","time":"2012-03-08T12:59:57Z","chapterIndex":8,"lessonOrQuestionIndex":0}}];
tokens[153] = [{"token":167,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed734b03","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 9 Lesson 1","time":"2012-03-08T12:59:59Z","chapterIndex":8,"lessonOrQuestionIndex":0}}];
tokens[154] = [{"token":168,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7357f2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 9 Lesson 2","time":"2012-03-08T13:00:00Z","chapterIndex":8,"lessonOrQuestionIndex":1}}];
tokens[155] = [{"token":169,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7357f2","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 9 Lesson 2","time":"2012-03-08T13:00:00Z","chapterIndex":8,"lessonOrQuestionIndex":1}}];
tokens[156] = [{"token":170,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7369ef","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 9 Lesson 3","time":"2012-03-08T13:00:01Z","chapterIndex":8,"lessonOrQuestionIndex":2}}];
tokens[157] = [{"token":171,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed7369ef","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 9 Lesson 3","time":"2012-03-08T13:00:01Z","chapterIndex":8,"lessonOrQuestionIndex":2}}];
tokens[158] = [{"token":172,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed737fc4","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lesson","courseItemState":"start","contentName":"Chapter 9 Lesson 4","time":"2012-03-08T13:00:02Z","chapterIndex":8,"lessonOrQuestionIndex":3}}];
tokens[159] = [{"token":173,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed737fc4","contentType":"lesson","certificateCourseId":"","contentData":null,"interactionKey":"lessonEndMenu","courseItemState":"end","contentName":"Chapter 9 Lesson 4","time":"2012-03-08T13:00:02Z","chapterIndex":8,"lessonOrQuestionIndex":3}}];
tokens[160] = [{"token":174,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed732634","contentType":"quiz","certificateCourseId":"","contentData":null,"interactionKey":"startQuiz","courseItemState":"start","contentName":"Chapter 9","time":"2012-03-08T13:00:03Z","chapterIndex":8,"lessonOrQuestionIndex":3}}];
tokens[161] = [{"token":175,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:03Z","chapterIndex":8,"lessonOrQuestionIndex":4}}];
tokens[162] = [{"token":176,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T13:00:04Z","chapterIndex":8,"lessonOrQuestionIndex":4}}];
tokens[163] = [{"token":177,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:04Z","chapterIndex":8,"lessonOrQuestionIndex":5}}];
tokens[164] = [{"token":178,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T13:00:05Z","chapterIndex":8,"lessonOrQuestionIndex":5}}];
tokens[165] = [{"token":179,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:05Z","chapterIndex":8,"lessonOrQuestionIndex":6}}];
tokens[166] = [{"token":180,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T13:00:06Z","chapterIndex":8,"lessonOrQuestionIndex":6}}];
tokens[167] = [{"token":181,"type":"ccState","data":{"result":false,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"poseQuestion","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:09Z","chapterIndex":8,"lessonOrQuestionIndex":7}}];
tokens[168] = [{"token":182,"type":"ccState","data":{"result":true,"questionResponse":"2","contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playAnswerExplanation","courseItemState":"start","contentName":null,"time":"2012-03-08T13:00:10Z","chapterIndex":8,"lessonOrQuestionIndex":7}}];
tokens[169] = [{"token":183,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed732634","contentType":"quiz","certificateCourseId":"","contentData":"2","interactionKey":"reportChapterScore","courseItemState":"end","contentName":"Chapter 9","time":"2012-03-08T13:00:11Z","chapterIndex":8,"lessonOrQuestionIndex":7}}];
tokens[170] = [{"token":184,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":"0cccd9b516233e4bb1c6c04fed732634","contentType":"chapter","certificateCourseId":"","contentData":null,"interactionKey":"endOfChapterMenu","courseItemState":"end","contentName":"Chapter 9","time":"2012-03-08T13:00:12Z","chapterIndex":8,"lessonOrQuestionIndex":7}}];
tokens[171] = [{"token":185,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playThanks","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:17Z","chapterIndex":9,"lessonOrQuestionIndex":0}}];
tokens[172] = [{"token":186,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playFinalScore","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:30Z","chapterIndex":9,"lessonOrQuestionIndex":0}}];
tokens[173] = [{"token":187,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":null,"certificateCourseId":"","contentData":null,"interactionKey":"playCourseResult","courseItemState":null,"contentName":null,"time":"2012-03-08T13:00:38Z","chapterIndex":9,"lessonOrQuestionIndex":0}}];
tokens[174] = [{"token":188,"type":"ccState","data":{"result":null,"questionResponse":null,"contentId":null,"contentType":"course","certificateCourseId":"","contentData":null,"interactionKey":null,"courseItemState":"end","contentName":null,"time":"2012-03-08T13:00:52Z","chapterIndex":null,"lessonOrQuestionIndex":null}}];
tokens[175] = [{"token":189,"type":"callDuration","data":{"callEvent":"DISCONNECT","time":1331211652263}}];


for(var i = 0; i < tokens.length; ++i) {
    var token = tokens[i];
    for(var j = 0; j < token.length; ++j) {
        var dataToken = token[j];
        if(dataToken.type == "ccState" && dataToken.data.contentId != null) {
            var data = dataToken.data;
            var contentName = data.contentName;
            var contentType = data.contentType;

            if(contentType == "quiz") {
                contentType = "chapter";
            }

            if(contentType == "chapter") {
                var chapterNode = courseData.children[data.chapterIndex];
                data.contentId = chapterNode.id;
            } else if (contentType == "lesson") {
                var lessonNode = courseData.children[data.chapterIndex].children[data.lessonOrQuestionIndex];
                data.contentId = lessonNode.id;
            }
        }
    }
}

addAudioTokenWithId = function(contentId, token, data){
    token.push({
                "token": 0,
                "type": "audioTracker",
                "data": {
                    "contentId": contentId,
                    "timeStamp": data.time,
                    "duration" : Math.floor((Math.random()*1000)+1)
                }
            });
}

for(var i = 0; i < tokens.length; ++i) {
    var token = tokens[i];
    for(var j = 0; j < token.length; ++j) {
        var dataToken = token[j];
        if(dataToken.type == "ccState") {
            var data = dataToken.data;
            if(data.courseItemState == "end") {
                var contentType = data.contentType;
                if(contentType == "chapter"){
                    var chapterNode = courseData.children[data.chapterIndex];
                    var chapterContents = chapterNode.contents;
                    for(var content in chapterContents){
                        addAudioTokenWithId(chapterContents[content].id, token, data)
                    }
                } else if(contentType == "quiz"){
                    for(var questionIndex = 4; questionIndex < 8; ++questionIndex){
                        var chapterNode = courseData.children[data.chapterIndex].children[questionIndex];
                        var chapterContents = chapterNode.contents;
                        for(var content in chapterContents){
                            addAudioTokenWithId(chapterContents[content].id, token, data)
                        }
                    }

                } else if(contentType == "lesson"){
                    var lessonNode = courseData.children[data.chapterIndex].children[data.lessonOrQuestionIndex];
                    var lessonContents = lessonNode.contents;
                    for(var content in lessonContents){
                        addAudioTokenWithId(lessonContents[content].id, token, data)
                    }
                }
            }
        }
    }
}

//update tokens with token numbers
var tokenNum = 0;
for(var i = 0; i < tokens.length; ++i) {
    var token = tokens[i];
    for(var j = 0; j < token.length; ++j) {
        var dataToken = token[j];
        dataToken.token = tokenNum++;
    }
}

var Utility = function() {
    this.stringify = function(value) {
        switch (typeof value) {
            case 'string':
                return this.quote(value);
            case 'number':
            case 'boolean':
            case 'null':
                return value;
            case 'object':
                if(!value) {
                    return value;
                }

                if(value instanceof Array) {
                    var result = "[";
                    for(var i = 0; i < value.length; ++i) {
                        result += this.stringify(value[i]) + ',';
                    }
                    result = this.removeCharAtEnd(result,',') + "]";

                    return result;
                } else {
                    return this.objectToString(value);
                }
        }
    }

    this.objectToString = function(object) {
        var result = "{";
        for(var key in object) {
            var value = this.stringify(object[key]);
            result += this.quote(key) + ':';
            result += value + ',';
        }
        result = this.removeCharAtEnd(result,',') + "}";

        return result;
    }

    this.quote = function(string) {
        return "\"" + string + "\"";
    }

    this.removeCharAtEnd = function(value, c) {
        if((value.length > 0) && (value.charAt(value.length - 1) == c)) {
            return value.substring(0, value.length - 1);
        }
    }

    this.format = function() {
        var formatted = arguments[0];
        var i = 0;
        for(var arg = 1; arg < arguments.length; ++arg) {
            var index = arg - 1;
            formatted = formatted.replace("{" + index + "}", arguments[arg]);
        }
        return formatted;
    };

    /*
     * https://developer.mozilla.org/en/Core_JavaScript_1.5_Reference:Global_Objects:Date
     * YaaY to Mozilla!
     */
    this.toISODateString = function(d) {
        function pad(n){return n<10 ? '0'+n : n}
        return d.getUTCFullYear()+'-'
            + pad(d.getUTCMonth()+1)+'-'
            + pad(d.getUTCDate())+'T'
            + pad(d.getUTCHours())+':'
            + pad(d.getUTCMinutes())+':'
            + pad(d.getUTCSeconds())+'Z'
    }
};

var utility = new Utility();

var flattened_tokens = []
var j = 0;
for (i = 0; i < tokens.length; i++) {
    for (j = 0; j < tokens[i].length; j++) {
        flattened_tokens.push(tokens[i][j]);
    }
}

vars.put("tokens_block", utility.stringify(flattened_tokens));